development:
  adapter: postgresql
  encoding: unicode
  database: restaurant-backend

test: &test
  adapter: postgresql
  encoding: unicode
  database: restaurant-backend
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: restaurant-backend
  pool: 5
  host: localhost
  username: postgres
  password: postgres

  
